import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Stanislav',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Sector 9',
      category: 'longboards',
      image: '/images/p1.jpg',
      price: 320,
      countInStock: 10,
      brand: 'Generic Longboard Brand',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Arbor',
      category: 'longboards',
      image: '/images/p2.jpg',
      price: 400,
      countInStock: 20,
      brand: 'Generic Longboard Brand',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Loaded',
      category: 'longboards',
      image: '/images/p3.jpg',
      price: 280,
      countInStock: 0,
      brand: 'Generic Longboard Brand',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Prism',
      category: 'longboards',
      image: '/images/p4.jpg',
      price: 330,
      countInStock: 15,
      brand: 'Generic Longboard Brand',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Dusters',
      category: 'longboards',
      image: '/images/p5.jpg',
      price: 190,
      countInStock: 5,
      brand: 'Generic Longboard Brand',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Santa Cruz',
      category: 'longboards',
      image: '/images/p6.jpg',
      price: 555,
      countInStock: 12,
      brand: 'Generic Longboard Brand',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;